version: '3.7'
services:
  db:
    image: postgres:14
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
